# Generated by Django 6.0.7 on 2026-08-04 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('total_cards', models.IntegerField()),
                ('external_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('rarity', models.CharField(blank=True, max_length=50)),
                ('supertype', models.CharField(max_length=20)),
                ('image_url', models.URLField(blank=True)),
                ('external_id', models.CharField(max_length=50, unique=True)),
                ('card_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.set')),
            ],
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('source', models.CharField(max_length=50)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='cards.card')),
            ],
            options={
                'indexes': [models.Index(fields=['card', 'recorded_at'], name='cards_price_card_id_3e5298_idx')],
            },
        ),
    ]
