# Generated by Django 6.0.7 on 2026-08-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='abbreviation',
            field=models.CharField(default='', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
    ]
