# Generated by Django 6.0.7 on 2026-08-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_set_abbreviation_set_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='abbreviation',
            field=models.CharField(max_length=10),
        ),
    ]
