# Generated by Django 6.0.7 on 2026-08-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_set_abbreviation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='supertype',
        ),
        migrations.AddField(
            model_name='card',
            name='artist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
